### ISSUE TITLE
README doesn't say if it's URP, HDRP or built-in

### ISSUE THREAD

**Issue by andybak** [provencher/MRTK-StandardShader#1]
I'm guessing the latter because if it wasn't you'd probably say.

However - as the built-in renderer becomes more and more sunsetted, it's going to become more confusing for people when projects don't explicitly state which renderers they are compatible with.

**Comment by provencher** [comment]
That's a fair statement. That said, this is an extension to MRTK, which defaults to the default renderer, and has an upgrade path to the now deprecated LWRP. If you find that confusing or ambiguous, feel free to file some feedback reports to them.

On it's own, this extension doesn't have a hard dependency on any render pipeline, but the supplied materials are built for the default renderer pipeline. The config file I mention in the readme allows you to replace the materials with your own.

**Comment by provencher** [comment]
Cheers, I clarified this in the readme. Thanks for taking the time to mention it.
