### ISSUE TITLE
Can this be used on Android?

### ISSUE THREAD

**Issue by elblogbruno** [provencher/MRTK-StandardShader#2]
Hello, thanks for sharing this repo it is very useful!
Do you know if it can be used for android or Ios?
Also, below standard, there's a TextMeshPro Shader what is it used for?
Thanks
Bruno

**Comment by provencher** [comment]
Hi @elblogbruno!

I'm glad this is helpful to you!
Yes this can be used on Android and iOS, as MRTK officially supports ARFoundation.
I recommend reading on their [documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_MRTKStandardShader.html). Also, I make use of this shader with [MRTK-Quest](https://github.com/provencher/MRTK-Quest).

The TextMeshPro shader is there to enable Single pass stereo instancing on mixed reality hardware, which the default TextMeshPro shader doesn't support.

Hope that helps,
Eric

**Comment by elblogbruno** [comment]
Thanks! Sorry for answering to late!
